
version: 2.1
orbs:
  node: circleci/node@latest

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager:npm
      - run:
          command: npm run build
          name: Run tests
      - run:
          command: npm run test
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
